admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }

admin_listVet:
    path:     /listVet
    defaults: { _controller: AdminBundle:listVet_Dress_Admin:list }

index:
    path:     /home
    defaults: { _controller: AdminBundle:Default:index }
