admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }

admin_listVet:
    path:     /listVet
    defaults: { _controller: AdminBundle:listVet_Dress_Admin:list }

index:
    path:     /home
    defaults: { _controller: AdminBundle:Default:index }

<<<<<<< HEAD
admin_animeaux:
    path:     /useranimeaux
    defaults: { _controller: AdminBundle:AdminGateau:animal }

admin_sos:
    path:     /sos
    defaults: { _controller: AdminBundle:AdminGateau:sosList }

admin_user:
    path:     /users
    defaults: { _controller: AdminBundle:AdminGateau:user }

admin_sos_delete:
    path:     /sos/delete/{id}
    defaults: { _controller: AdminBundle:AdminGateau:delete }


admin_sos_animal:
    path:     /useranimeaux/delete/{id}
    defaults: { _controller: AdminBundle:AdminGateau:deleteAnimal }


admin_user_delete:
    path:     /users/delete/{id}
    defaults: { _controller: AdminBundle:AdminGateau:deleteUser }




=======
confirmer:
    path:     /conf/{id}
    defaults: { _controller: AdminBundle:listVet_Dress_Admin:ConfirmerUser }

block:
    path:     /block/{id}
    defaults: { _controller: AdminBundle:listVet_Dress_Admin:blockUser }

Back_Concours_index:
    path:     /concours
    defaults: { _controller: AdminBundle:concours:index }

Back_Concours_new:
    path:     /concours/new
    defaults: { _controller: AdminBundle:concours:new }

Back_concours_show:
    path:     /concours/show/{id}
    defaults: { _controller: AdminBundle:concours:show }
Back_concours_edit:
    path:     /concours/edit/{id}
    defaults: { _controller: AdminBundle:concours:edit }
Back_concours_delete:
    path:     /concours/delete/{id}
    defaults: { _controller: AdminBundle:concours:delete }
concours_d:
    path:     /demande
    defaults: { _controller: AdminBundle:concours:houssem }



concours_edit_participant:
    path:     /{id}/accepter
    defaults: { _controller: AdminBundle:concours:accept }


concours_delete_particpant:
    path:     /{id}/refuser
    defaults: { _controller: AdminBundle:concours:refuser }
>>>>>>> aecd55095bfd9a8ec3d097f9c8ac1652a7938404

