fiche_de_soin:
    resource: "@FicheDeSoinBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation


#FosUser_Routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml
