front_end_vet:
    path:     /veterinaires
    defaults: { _controller: VeterinaireBundle:Default:list }


front_end_show_vet:
    path:     /veterinaire/{id}
    defaults: { _controller: VeterinaireBundle:Default:showVet }



aff_Calendrier:
    path:     /cal
    defaults: { _controller: VeterinaireBundle:Calender:index }