fiche_de_soin_homepage:
    path:     /
    defaults: { _controller: FicheDeSoinBundle:Default:index }



vetno active:
    path:     /noActiv
    defaults: { _controller: FicheDeSoinBundle:Default:notActived }

rech:
    path:     /find
    defaults: { _controller: VeterinaireBundle:Default:recherchePArnom }